### ISSUE TITLE
EOF occurred while reading control socket

### ISSUE THREAD

**Issue by B00ze64** [cynicastic/scribe#6]
Good day.

Updated Scribe from v0.94 to current release today on AC3200 Merlin 384.x. Everything works, but I get errors when accessing the control socket file. If I try to reload syslog-ng.conf, I get "EOF occurred while reading control socket." I found /opt/sbin/syslog-ng-ctl, and I can read it myself, but it's binary. No idea what's wrong...

Regards,

**Comment by cynicastic** [comment]
> Good day.
> 
> Updated Scribe from v0.94 to current release today on AC3200 Merlin 384.x. Everything works, but I get errors when accessing the control socket file. If I try to reload syslog-ng.conf, I get "EOF occurred while reading control socket." I found /opt/sbin/syslog-ng-ctl, and I can read it myself, but it's binary. No idea what's wrong...
> 
> Regards,

Sorry for the far too long delay in responding.  I'm pretty sure that's an error in Entware's 3.23 version of syslog-ng itself, on the armv71 platform.  It works correctly on the aarch64 (e.g. 86U) platform.  The good news is that it seems to have no effect on the actual working of syslog-ng.

Coming from a version that long ago, I'd recommend uninstalling and re-installing scribe, rather than using scribe's update (not sure which way you upgraded).  There were some significant changes along the way, so I'm not 100% sure just an update will work correctly.   However, uninstalling and re-installing won't fix the error you're encountering, my test router is an AC3200 and I've installed from scratch a few times testing the next version.

If you're not already there, there is community support at https://www.snbforums.com/threads/scribe-syslog-ng-and-logrotate-installer.55853/ - I've been incredibly busy with other things most of this year and there are people there who are really good at troubleshooting.  I need to put that in the README, I know.
